server:
  # 服务端口
  port: 5001

spring:
  thymeleaf:
    cache: false # 关闭缓存
  # 数据源配置
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3307/luoqiu-security?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    driver-class-name: com.mysql.cj.jdbc.Driver



luoqiu:
  security:
    authentication:
      loginPage: /login/page # 响应认证(登录)页面URL
      loginProcessingUrl: /login/form  # 登录表单提交处理Url 12345678
      usernameParameter: name # 登录表单用户名的属性名
      passwordParameter: pwd # 登录表单密码的属性名
      staticPaths: # 静态资源 "/dist/**", "/modules/**", "/plugins/**"
        - /dist/**
        - /modules/**
        - /plugins/**
      loginType: REDIRECT # 认证之后 响应的类型：JSON/REDIRECT
